### ISSUE TITLE
Drop modules for Java < 8

### ISSUE THREAD

**Issue by slachiewicz** [mojohaus/keytool#42] opened 2022-04-22 20:10 UTC

**Comment by bmarwell** [comment] 2022-04-23 10:52
+1, but that should go into a v3.0.0 in my opinion.
While at it, we could update the minimum maven version as well and drop Maven v2 support. WDYT?

**Comment by slachiewicz** [comment] 2022-04-23 11:06
Yes let's do cleanup quickly

**Comment by bmarwell** [comment] 2022-04-23 20:24
This one would be a good cleanup,, we could merge this issue #42: 
https://github.com/mojohaus/keytool/issues/14#issuecomment-1107552600

**Comment by olamy** [comment] 2022-04-24 00:06
+1

**Comment by bmarwell** [comment] 2022-04-24 08:17
Ok. Closing this as a duplicate of #14. Will update #14 accordingly.

**Closed** 2022-04-24 12:44 UTC
